[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/blog/graphql-file-uploading/"
  to = "/posts/graphql-file-uploading/"

[[redirects]]
  from = "/blog/valid-https-certificate-for-local-home-assistant-installation/"
  to = "/posts/valid-https-certificate-for-local-home-assistant-installation/"

[[redirects]]
  from = "/blog/motioneye-in-home-assistant/"
  to = "/posts/motioneye-in-home-assistant/"

[[redirects]]
  from = "/blog/"
  to = "/"

[[redirects]]
  from = "/blog/tags/*"
  to = "/"
